@startuml

participant "Client"
participant "Service Provider" as SP
participant "Authorization Provider" as AP

Client -> SP: POST /radiodns/tag/1/tag
SP -> AP: POST /authorized
SP <-- AP: 200 OK
Client <-- SP: 200 OK

@enduml
