@startuml

participant "Client"
participant "Service Provider" as SP
participant "Authorization Provider" as AP

Client -> AP: POST /register
Client <-- AP: 201 Created

|||

Client -> AP: POST /token
Client <-- AP: 200 OK

@enduml
