@startuml

participant "Client"
participant "Service Provider" as SP
participant "Authorization Provider" as AP

Client -> SP: POST /radiodns/tag/1/tag
SP -> AP: POST /authorized
SP <-- AP: 404 Not Found
Client <-- SP: 401 Unauthorized

@enduml
