jupyter:
  image: jupyter/notebook
  ports:
    - "9000:9000"
  expose:
    - "9000"
  volumes:
    - tutorial:/opt/notebooks/tutorial
  command: ipython notebook --port 9000 --ip=0.0.0.0 --no-browser --notebook-dir=/opt/notebooks

