jupyter:
  image: ebutech/jupyter-cpa-tutorial
  ports:
    - "9000:9000"
  expose:
    - "9000"
  volumes:
    - ./tutorial:/opt/notebooks/tutorial          # Notebooks
    - /var/run/docker.sock:/var/run/docker.sock   # Used to restart the AP
    - .:/opt/docker                               # Used to write /opt/docker/github_credentials.yml

  command: sh -c 'ipython notebook --profile=default --NotebookApp.port=9000 --no-browser --notebook-dir=/opt/notebooks --ip=* --debug'
  links:
    - authprovider:ap
    - serviceprovider:sp


authprovider:
  image: ebutech/cpa-auth-provider:latest
  extends:
    file: github_credentials.yml
    service: authprovider
  environment:
    CPA_CLIENT_URL: <TODO>
    PORT: 8001
  ports:
    - "8001:8001"
  expose:
    - "8001"
  restart: always


serviceprovider:
  image: ebutech/cpa-service-provider:latest
  environment:
    CPA_AUTH_PROVIDER_URL: http://ap:8001
    CPA_SERVICE_PROVIDER_DOMAIN: localhost:8002
    PORT: 8002
  ports:
    - "8002:8002"
  expose:
    - "8002"
  links:
    - authprovider:ap


